# Generated by Django 5.1.3 on 2025-01-07 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="emr.schedule",
            ),
        ),
    ]
