# Generated by Django 5.1.3 on 2025-01-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0006_alter_patient_blood_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenbooking",
            name="previous_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emr.tokenbooking",
            ),
        ),
    ]
