# Generated by Django 5.1.4 on 2025-01-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0010_facilitylocation_facilitylocationorganization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitylocation',
            name='location_type',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
