# Generated by Django 6.0 on 2026-09-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0082_remove_encounter_encounter_class_history"),
        ("emr", "0088_merge_20260820_1435"),
    ]

    operations = []
